# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('headimg', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=256, unique=True)),
                ('addr', models.CharField(max_length=200)),
            ],
            options={
                'db_table': ' axf_user',
            },
        ),
    ]
