# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=False),
        ),
    ]
